version: "3.7"

volumes:
  data: {}

services:
  relay:
    image: scsibug/nostr-rs-relay:0.8.13
    volumes:
      - ./relay-config.toml:/usr/src/app/config.toml
      - data:/usr/src/app/db
  dns:
    build: .
    ports:
      - 10053:10053
    depends_on:
      - relay
    environment:
      CACHE_RELAY: relay:8080
      BOOTSTRAP_RELAYS: wss://nostrue.com/,wss://nos.lol/,wss://nostr.wine/
